version: 0.2

phases:
  install:
    commands:
      - amazon-linux-extras install epel -y
      - yum install -y cpio yum-utils zip
      - repoquery --whatprovides '*/libcrypt.so.1'
  build:
    commands:
     - mkdir -p ./build
     - cd ./build
     - yumdownloader -x \*i686 --resolve --archlist=x86_64 clamav clamav-lib bzip2-libs libidn2 nss libcrypt cyrus-sasl-lib libssh2 libunistring libnghttp2 openldap clamav-update xz-libs json-c libtool-ltdl openssl openssl-devel libcurl-devel zlib-devel libpng-devel libxml2-devel json-c-devel bzip2-devel ncurses-devel pcre2 libxml2 libprelude gnutls libtasn1 nettle
     - find . -name "*.rpm" -exec sh -c "rpm2cpio {} | cpio -vimd" \;
     - cd ..
  post_build:
    commands:
      - mkdir -p ./build/bin
      - mkdir -p ./build/lib
      - mv ./build/usr/bin/clamscan ./build/usr/bin/freshclam ./build/bin/.
      - mv ./build/usr/lib64/libcrypt.so ./build/lib/libcrypt.so.1
      - mv ./build/usr/lib64/* ./build/lib/.
      - mv freshclam.conf clamd.conf build/bin/.
artifacts:
  files:
   - build/bin/**/*
   - build/lib/**/*
