version: 0.2

phases:
  install:
    commands:
      - amazon-linux-extras install epel -y
      - yum install -y cpio yum-utils zip
  build:
    commands:
     - mkdir -p ./build
     - cd ./build
     - yumdownloader -x \*i686 --archlist=x86_64 clamav cyrus-sasl-lib libunistring clamav-lib openldap libssh2 nss clamav-update json-c pcre2 libxml2 bzip2-libs libidn2 libtool-ltdl xz-libs libprelude libnghttp2 nettle gnutls libcurl
     - rpm2cpio clamav-0*.rpm | cpio -vimd
     - rpm2cpio clamav-lib*.rpm | cpio -vimd
     - rpm2cpio clamav-update*.rpm | cpio -vimd
     - rpm2cpio json-c*.rpm | cpio -vimd
     - rpm2cpio pcre*.rpm | cpio -vimd
     - rpm2cpio libxml2*.rpm | cpio -vimd
     - rpm2cpio bzip2-libs*.rpm | cpio -vimd
     - rpm2cpio libtool-ltdl*.rpm | cpio -vimd
     - rpm2cpio xz-libs*.rpm | cpio -vimd
     - rpm2cpio libprelude*.rpm | cpio -vimd
     - rpm2cpio gnutls*.rpm | cpio -vimd
     - rpm2cpio libcurl*.rpm | cpio -vimd
     - rpm2cpio nettle*.rpm | cpio -vimd
     - rpm2cpio libnghttp2*.rpm | cpio -vimd
     - rpm2cpio libssh2*.rpm | cpio -vimd
     - rpm2cpio libidn2*.rpm | cpio -vimd
     - rpm2cpio openldap*.rpm | cpio -vimd
     - rpm2cpio libunistring*.rpm | cpio -vimd
     - rpm2cpio cyrus-sasl-lib*.rpm | cpio -vimd
     - rpm2cpio nss*.rpm | cpio -vimd
     - cd ..
  post_build:
    commands:
      - mkdir -p ./build/bin
      - mkdir -p ./build/lib
      - mv ./build/usr/bin/clamscan ./build/usr/bin/freshclam ./build/bin/.
      - mv ./build/usr/lib64/* ./build/lib/.
      - mv freshclam.conf clamd.conf build/bin/.
artifacts:
  files:
   - build/bin/**/*
   - build/lib/**/*