version: 0.2

phases:
  install:
    commands:
      - amazon-linux-extras install epel -y
      - yum install -y cpio yum-utils zip
  build:
    commands:
     - mkdir -p ./build
     - cd ./build
     - yumdownloader -x \*i686 --resolve --archlist=x86_64 clamav clamav-lib clamav-update json-c pcre2 libprelude gnutls libtasn1 lib64nettle nettle
     - find . -name "*.rpm" -exec sh -c "rpm2cpio {} | cpio -vimd" \;
     - cd ..
  post_build:
    commands:
      - mkdir -p ./build/bin
      - mkdir -p ./build/lib
      - mv ./build/usr/bin/clamscan ./build/usr/bin/freshclam ./build/bin/.
      - mv ./build/usr/lib64/* ./build/lib/.
      - mv freshclam.conf clamd.conf build/bin/.
artifacts:
  files:
   - build/bin/**/*
   - build/lib/**/*